# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kjell < Formula
  desc "Shell command classifier for AI coding agents"
  homepage "https://github.com/agentbellnorm/kjell"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.2.1/kjell_0.2.1_darwin_amd64.tar.gz"
      sha256 "09d44f11e134ea4c007f07f2e976d3ba4ae09b5dc39670ce9f87efd21bd7bd99"

      define_method(:install) do
        bin.install "kjell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.2.1/kjell_0.2.1_darwin_arm64.tar.gz"
      sha256 "ffefc2c80c7a91140d15d976aa17c0a749864a49bf130a1c7bec181eb0e4af02"

      define_method(:install) do
        bin.install "kjell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.2.1/kjell_0.2.1_linux_amd64.tar.gz"
      sha256 "0ac7194225b9d81a54b91f5c6048faf41cb4bfa23456a941eb0df240fedb4232"
      define_method(:install) do
        bin.install "kjell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.2.1/kjell_0.2.1_linux_arm64.tar.gz"
      sha256 "775f947a305e7b7dcc50f47e06d0a1e17ec2cbc99e2ca7862e347d965c6daeb7"
      define_method(:install) do
        bin.install "kjell"
      end
    end
  end
end
