# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kjell < Formula
  desc "Shell command classifier for AI coding agents"
  homepage "https://github.com/agentbellnorm/kjell"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.3.1/kjell_0.3.1_darwin_amd64.tar.gz"
      sha256 "2050f02737bfe6c3b89b4438dd045e805f207b77f8890ef494a27f2456e704df"

      define_method(:install) do
        bin.install "kjell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.3.1/kjell_0.3.1_darwin_arm64.tar.gz"
      sha256 "27488d3c3f669e9fde2f68a401b7c57be0ac179c3852587d6e57da9ca67f987b"

      define_method(:install) do
        bin.install "kjell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.3.1/kjell_0.3.1_linux_amd64.tar.gz"
      sha256 "24bd7b6215b9dd0759ae07c9224f59a881ccc4a0ffe006330ca74000c4da87ce"
      define_method(:install) do
        bin.install "kjell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentbellnorm/kjell/releases/download/v0.3.1/kjell_0.3.1_linux_arm64.tar.gz"
      sha256 "f35640019b77735d2237d59f617da7b3d0db54d97619622dbdb5b68491b5fed1"
      define_method(:install) do
        bin.install "kjell"
      end
    end
  end
end
